I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    ao "וואה וואה מה זה פה"
Exception: Sayer 'ao' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script
    ao "וואה וואה מה זה פה"
  File "E:\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "E:\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'ao' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Otomai 1.0
Mon Nov  4 18:46:53 2024
